### ISSUE TITLE
Extract and translate Effective and Binding Set of Capabilities.

### ISSUE THREAD

**Issue by rhatdan** [containers/psgo#11]
Most people have no idea what capabilities their processes or containers are running with.
Extracting the data out of /proc/PID/status you get 
CapEff
CapBind
These are bit maps, need to translate these bitmaps into something humans can understand.
pscap does this now.

**Comment by vrothberg** [comment]
@rhatdan Let's assume we have a format descriptor for each set of capabilities, how should we print the results? A comma-separated list like "CAP_A, CAP_B, CAP_C"?

A format string like `"pid, capeff"` would then return:
```
PID    CapEFF
1        CAP_A, CAP_B, CAP_C, [...]
2        [...]
```

**Comment by rhatdan** [comment]
```
pscap | head
ppid  pid   name        command           capabilities
1     752   root        systemd-journal   chown, dac_override, dac_read_search, fowner, setgid, setuid, sys_ptrace, sys_admin, audit_control, mac_override, syslog, audit_read
1     776   root        systemd-udevd     full
1     971   root        auditd            full
971   973   root        audispd           full
1     996   root        systemd-machine   chown, dac_override, dac_read_search, fowner, fsetid, kill, setgid, sys_chroot, sys_ptrace, sys_admin, mknod
1     997   root        sssd              chown, dac_read_search, fowner, kill, setgid, setuid, net_admin, ipc_lock, sys_admin, sys_nice, sys_resource, block_suspend
1     999   root        bluetoothd        net_bind_service, net_admin
1     1001  root        iio-sensor-prox   chown, dac_override, dac_read_search, fowner, fsetid, kill, setgid, setuid, setpcap, linux_immutable, net_bind_service, net_broadcast, net_admin, net_raw, ipc_lock, ipc_owner, sys_rawio, sys_chroot, sys_ptrace, sys_pacct, sys_admin, sys_boot, sys_nice, sys_resource, sys_time, sys_tty_config, mknod, lease, audit_write, audit_control, setfcap, mac_override, mac_admin, syslog, wake_alarm, block_suspend, audit_read
1     1003  rtkit       rtkit-daemon      dac_read_search, sys_ptrace, sys_nice
```

**Comment by rhatdan** [comment]
Something like pscap

**Comment by vrothberg** [comment]
@rhatdan, thanks. In comparison to `pscap` I suggest to print the caps in capital letters so that they can easily be copied from and to `--cap-{add,drop}`.

**Comment by rhatdan** [comment]
SGTM, although I think both cases work in cap-add/drop

**Comment by rhatdan** [comment]
For now, All I care about is capEff and capBnd.  The others you have to google everytime.
Eff is the set you got, and Bnd is the set you could get.
They are usually the same when running as root, and different when you have a process running as a user uid. 

Although I believe in the podman and potentially docker case, if you run with a --user dwalsh flag, you end up with no capabiltiies, rather then in the case where you log into your laptop and you end up with capEff being none, but capBnd being all.
