### ISSUE TITLE
Add a huser hgroup to show host USER and host Group when running in UserNamespace

### ISSUE THREAD

**Issue by rhatdan** [containers/psgo#23]
This could help users understand what is going on within the container when using something like podman top.

**Comment by vrothberg** [comment]
Great idea, as always. I think this would require to change the logic of psgo a bit as we need to extract that from the host (same for https://github.com/containers/psgo/issues/22).

Currently, we join the namespace and then extract all data from there. Now, we may need to differentiate between host and non-host descriptors and extract the data in the corresponding contexts.
