### ISSUE TITLE
compatibility to Docker and ps (1) and more

### ISSUE THREAD

**Issue by vrothberg** [containers/psgo#3]
I want to use this issue to discuss if and to which extent we aim to be compatible with Docker and ps (1). There are several issues that we might need to sort out depending on the decision (all mentioned below).

### docker-top
The output of docker-top uses more space than necessary (because the way `text/tabwriter` is used):
```
# docker run -d alpine sleep 100
196ced4826d9d4a4e9f8f307878c9362a2c0cf85a6033db7a77d33ece9e1b082
# docker top 196ced4826d9d4a4e9f8f307878c9362a2c0cf85a6033db7a77d33ece9e1b082
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD      
root                19247               19230               0                   12:36               ?                   00:00:00            sleep 100
```

Do we want to keep the same configuration of the tabular out?

(my personal opinion: no, we should compress it a bit more so it's readable on a normal-sized terminal)

### time format
ps (1) returns the elapsed time and cpu time in the `[[DD-]hh:]mm:ss` form. Currently, we are returning the `time.Duration` format which is something like `9h49m21.457862147s`.

Shall we change the format? It would require some additional logic to calcuate it.

(my personal opinion: no, we're in golang and could remain compatible to the `time` package of the stdlib)

### `/proc` parsing
Currenlty, we are using `github.com/shirou/gopsutil` for most of the `/proc` parsing, which does a great job and allows to do much more than we need. However, one thing is currently missing, namely to extract the process group ID (ppid) forcing `processPGID(...)` in ps/ps.go to parse `/proc/$pid/stat`. This is a race condition since the process could already be dead (and already led to a failing Travis job).

Hence the question: Shall we do the `/proc` parsing here or keep using `github.com/shirou/gopsutil`?

(my opinion: I have a slight tendency to do the parsing on our own, so we can deal with consistently with race conditions. It also would avoid some hops in case we want to extend the library. Some fields in `/proc/$pid/stat`, for instance, are only visible by certain versions of Linux.)

Cc: @rhatdan @mheon @baude

**Comment by rhatdan** [comment]
I agree on compressing it.  I would leave the time format as is, or perhaps provide a helper function for a tool like podman to convert.
If you have the time to do /proc parsing, that works for me.  It would be more a concern about how quickly this can get done.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
parsing `/proc` sounds fine, but wouldn't there be always some race condition if you also want to read the cmdline (through `/proc/$PID/cmdline`)?  That information doesn't seem present in `/proc/$PID/stat`

**Comment by rhatdan** [comment]
Right we only want to be as good as the ps command, which I beleive does not have any magic bullets for this.

**Comment by vrothberg** [comment]
> parsing /proc sounds fine, but wouldn't there be always some race condition if you also want to read the cmdline (through /proc/$PID/cmdline)? That information doesn't seem present in /proc/$PID/stat

Yes, there will always be one; I think we'd also need to extract some data from `/proc/$pid/status`. But we can deal with it in a consistent way (e.g., throw a `ErrNoSuchPID` and skip the given process).

**Comment by vrothberg** [comment]
Thanks for the feedback. I opened two issues to track them separately:

- https://github.com/containers/psgo/issues/8
- https://github.com/containers/psgo/issues/7
