### ISSUE TITLE
psgo is not getting the USER inside of the usernamespace

### ISSUE THREAD

**Issue by rhatdan** [containers/psgo#35]
sh-4.4# podman run -d --uidmap 0:100000:5000 fedora sleep 1000
7d54a703ca278cbef43c5072f44d8c39622b4216e9d8b64bf04842038aff61b3
sh-4.4# podman top --latest user huser
USER     HUSER
100000   100000

You need to go into the User Namespace and the mount namespace of the container before collecting this information.

HUSER needs to be collected on the outside obviously.

**Comment by vrothberg** [comment]
Good catch, I'll give it a shot.
