### ISSUE TITLE
Would you support exposing Starttime?

### ISSUE THREAD

**Issue by haircommander** [containers/psgo#61]
Some background:

I'm working on a conmon monitoring loop in CRI-O to make sure we catch conmon OOMs in https://github.com/cri-o/cri-o/pull/3022. We want to be absolutely sure that the conmon PID we have saved is that which is attached to the container. We have a couple of heuristics that do so, and psgo is a great way to filter those heuristics.

One thing I wish psgo already supported is exposing starttime. etime would require some calculation and depends on a consistent string format to compare (last-saved-etime + elapsed time == etime). 

I thought about using the Process structure directly, but it's internal/ so I can't import it.

Left with no other choice, I come here, on my knees, begging for the start time to be exposed via the API, even though it's not techincally in the AIX format.

WDYT?

**Comment by rhatdan** [comment]
Sounds good to me.  @vrothberg WDYT?

**Comment by vrothberg** [comment]
Sure, sounds good! I opened https://github.com/containers/psgo/pull/62 to add support for extracting the start times.

> I thought about using the Process structure directly, but it's internal/ so I can't import it.

 Now everybody can use the new descriptor. That's why the implementation is internal :^)

**Comment by vrothberg** [comment]
@haircommander, you can fetch a fresh v1.4.0 now: https://github.com/containers/psgo/releases/tag/v1.4.0
