### ISSUE TITLE
COMM does not behave like in ps(1)

### ISSUE THREAD

**Issue by leahneukirchen** [containers/psgo#65]
psgo's COMM also parses /proc/.../cmdline, but ps(1) uses the 2nd field from /proc/.../stat.
This makes a difference when a program modifies argv[0].

**Comment by vrothberg** [comment]
Thanks for reaching out, @leahneukirchen! Are you interested in opening a PR? We're already parsing `.../stat`, and can use that from COMM.

**Comment by leahneukirchen** [comment]
Can do later, yes. :) See also my other issue.
