### ISSUE TITLE
readStat is not robust

### ISSUE THREAD

**Issue by leahneukirchen** [containers/psgo#66]
proc.readStat simply splits the fields by whitespace, which is not robust if the process name contains whitespace.

The correct algorithm for parsing `/proc/.../stat` is:
1) find the location of the first `(`.
2) find the location of the first `)` **starting from the end**.
3) the text between these locations is COMM.
4) the integer before the first `(` is the PID.
5) split the rest and assign them sequently.

**Comment by rhatdan** [comment]
Interested in opening a PR?

**Comment by leahneukirchen** [comment]
Yes, already half done.

**Comment by rhatdan** [comment]
Super, I saw the other email and @vrothberg had already asked you.  Sorry for nagging, and thanks for the PR.
